### PR TITLE
Fix typo ("oconf" -> "conf")

### PR DESCRIPTION
**Pull request by kenballus**
Fixes a typo that prevents building.

Without this patch, building gives this error:
```
config.c:2521:4: error: call to undeclared function 'oconf_error_at_locus_range'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2521 |           oconf_error_at_locus_range(&arg->locus,
      |           ^
  AR       libpound.a
1 error generated.
```

I'm pretty sure this is a typo. It should be `conf_error_at_locus_range`.

### CODE REVIEW

**Comment by kenballus** [comment]
The build failure was introduced by d0cc07a157b17e2c5fc93767ac4f039c04ee0ab4

**Comment by graygnuorg** [comment]
Hi Ben,

Thanks a lot. Patch applied (commit 1804e202e4)
